#!/usr/bin/env python3
"""
Build amplifier-core wheel for browser embedding.

This script builds the amplifier-core wheel and outputs it in formats suitable
for browser-based Amplifier applications:

1. Raw .whl file - for web apps serving as static asset
2. Base64-encoded - for embedding in single-file HTML

Usage:
    # Build from local amplifier-core checkout
    python build-wheel.py --source ~/repos/amplifier-core --output ./dist
    
    # Build from GitHub
    python build-wheel.py --source github --output ./dist
    
    # Generate HTML snippet for embedding
    python build-wheel.py --source ~/repos/amplifier-core --output ./dist --html-snippet

Requirements:
    - Python 3.10+
    - uv (for building wheels)
"""

import argparse
import base64
import subprocess
import sys
import tempfile
from pathlib import Path
import shutil


def build_wheel_from_local(source_path: Path, output_dir: Path) -> Path:
    """Build wheel from local amplifier-core checkout."""
    print(f"Building wheel from {source_path}...")
    
    # Ensure output directory exists
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Build using uv
    result = subprocess.run(
        ["uv", "build", "--wheel", "--out-dir", str(output_dir)],
        cwd=source_path,
        capture_output=True,
        text=True
    )
    
    if result.returncode != 0:
        print(f"Error building wheel: {result.stderr}", file=sys.stderr)
        sys.exit(1)
    
    # Find the built wheel
    wheels = list(output_dir.glob("amplifier_core-*.whl"))
    if not wheels:
        print("Error: No wheel file found after build", file=sys.stderr)
        sys.exit(1)
    
    wheel_path = wheels[0]
    print(f"Built: {wheel_path}")
    return wheel_path


def build_wheel_from_github(output_dir: Path, ref: str = "main") -> Path:
    """Clone amplifier-core from GitHub and build wheel."""
    print(f"Cloning amplifier-core from GitHub (ref: {ref})...")
    
    with tempfile.TemporaryDirectory() as tmpdir:
        tmp_path = Path(tmpdir)
        clone_path = tmp_path / "amplifier-core"
        
        # Clone the repo
        result = subprocess.run(
            ["git", "clone", "--depth", "1", "--branch", ref,
             "https://github.com/microsoft/amplifier-core.git", str(clone_path)],
            capture_output=True,
            text=True
        )
        
        if result.returncode != 0:
            print(f"Error cloning repo: {result.stderr}", file=sys.stderr)
            sys.exit(1)
        
        return build_wheel_from_local(clone_path, output_dir)


def encode_wheel_base64(wheel_path: Path) -> str:
    """Encode wheel file as base64."""
    with open(wheel_path, "rb") as f:
        return base64.b64encode(f.read()).decode("ascii")


def generate_html_snippet(wheel_path: Path, base64_content: str) -> str:
    """Generate HTML snippet for embedding the wheel."""
    return f'''<!-- Embedded amplifier-core wheel: {wheel_path.name} -->
<!-- Generated by build-wheel.py -->
<script id="amplifier-wheel-b64" type="text/plain">
{base64_content}
</script>

<!-- Installation code -->
<script>
async function installAmplifierCore(pyodide) {{
    // Get base64-encoded wheel
    const wheelB64 = document.getElementById('amplifier-wheel-b64').textContent.trim();
    
    // Decode to bytes
    const wheelBytes = Uint8Array.from(atob(wheelB64), c => c.charCodeAt(0));
    
    // Write to Pyodide's virtual filesystem
    pyodide.FS.writeFile('/tmp/{wheel_path.name}', wheelBytes);
    
    // Install dependencies from PyPI, then amplifier-core from emfs:
    const micropip = pyodide.pyimport('micropip');
    await micropip.install(['pydantic', 'pyyaml', 'typing-extensions']);
    await micropip.install('emfs:/tmp/{wheel_path.name}');
    
    console.log('amplifier-core installed successfully!');
}}
</script>
'''


def main():
    parser = argparse.ArgumentParser(
        description="Build amplifier-core wheel for browser embedding"
    )
    parser.add_argument(
        "--source",
        required=True,
        help="Path to local amplifier-core checkout, or 'github' to clone from GitHub"
    )
    parser.add_argument(
        "--output",
        required=True,
        help="Output directory for wheel and generated files"
    )
    parser.add_argument(
        "--ref",
        default="main",
        help="Git ref to use when cloning from GitHub (default: main)"
    )
    parser.add_argument(
        "--html-snippet",
        action="store_true",
        help="Generate HTML snippet for embedding"
    )
    parser.add_argument(
        "--base64-only",
        action="store_true",
        help="Only output base64-encoded wheel (no raw .whl)"
    )
    
    args = parser.parse_args()
    output_dir = Path(args.output)
    
    # Build the wheel
    if args.source.lower() == "github":
        wheel_path = build_wheel_from_github(output_dir, args.ref)
    else:
        source_path = Path(args.source).expanduser().resolve()
        if not source_path.exists():
            print(f"Error: Source path does not exist: {source_path}", file=sys.stderr)
            sys.exit(1)
        wheel_path = build_wheel_from_local(source_path, output_dir)
    
    # Encode as base64
    print("Encoding wheel as base64...")
    base64_content = encode_wheel_base64(wheel_path)
    
    # Write base64 file
    base64_path = output_dir / f"{wheel_path.stem}.b64.txt"
    with open(base64_path, "w") as f:
        f.write(base64_content)
    print(f"Base64 output: {base64_path}")
    print(f"  Original size: {wheel_path.stat().st_size:,} bytes")
    print(f"  Base64 size: {len(base64_content):,} bytes ({len(base64_content) / wheel_path.stat().st_size:.1%} of original)")
    
    # Generate HTML snippet if requested
    if args.html_snippet:
        html_content = generate_html_snippet(wheel_path, base64_content)
        html_path = output_dir / "amplifier-wheel-embed.html"
        with open(html_path, "w") as f:
            f.write(html_content)
        print(f"HTML snippet: {html_path}")
    
    # Remove raw wheel if base64-only
    if args.base64_only:
        wheel_path.unlink()
        print("(Raw wheel removed, base64 only)")
    
    print("\nDone!")
    print("\nUsage:")
    print("  For web apps:       Copy .whl to /assets/ and install via micropip")
    print("  For single-file:    Copy contents of .b64.txt into <script> tag")
    if args.html_snippet:
        print(f"  HTML snippet:       Include {html_path.name} in your HTML")


if __name__ == "__main__":
    main()
